services:
    db:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: autoaudit
        ports:
            - '5433:5432'
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./db/autoaudit_schema.sql:/docker-entrypoint-initdb.d/autoaudit_schema.sql

    redis:
        image: redis:alpine
        restart: always
        ports:
            - '6379:6379'

    backend:
        build:
            context: ./backend
        ports:
            - '8000:8000'
        env_file:
            - .env
        depends_on:
            - db
            - redis

volumes:
    db_data:
